### ISSUE TITLE
Add job throttle to jenkins file

### ISSUE THREAD

**Issue by pkgdemon** [iXsystems/ixautomation#127]
![job throttle](https://user-images.githubusercontent.com/4109732/40566448-a85c8fb0-603e-11e8-954a-2f11d1a2c935.png)

**Comment by miwi-fbsd** [comment]
We're not able to archive this, throttle is not recommended in pipeline as of the date i write that, the other approve we tired was to use lock's but it turned out it failed during parallels build as explained [here](https://wiki.jenkins.io/display/JENKINS/Lockable+Resources+Plugin?focusedCommentId=138451514#comment-138451514)
